### ISSUE TITLE
Copy Writing Proposal 

### ISSUE THREAD

**Issue by Gallantmayor** [TeamMalaysia/Steemph.cebu#15]
Hello, i just checked your lovely project and i discovered you have some sections missing out like FAQ, about us, contact us and privacy policy. If you dont mind i will like to write that for you.
My email: gallantmayor22@gmail.com

**Comment by superoo7** [comment]
Personally speaking, I don't think I need this feature right now, maybe in the future. Thanks for stopping by, I will closed this issue.
